package cc.polarastrum.aiyatsbus.core.enchant

/**
 * Iweleth
 * cc.polarastrum.iweleth.listener.ActionType
 *
 * @author mical
 * @since 2025/8/6 15:12
 */
enum class EventType {
    TRIGGER,

    //PLAYER
    ATTACK_ENTITY,
    DAMAGED_BY_ENTITY,
    DAMAGED_BY_BLOCK,
    DAMAGED,
    CHAT,
    ADVANCEMENT_DONE,
    ARMORSTAND_MANIPULATE,
    BED_ENTER,
    BED_LEAVE,
    BUCKET_EMPTY,
    BUCKET_FILL,
    BUCKET_ENTITY,
    DROP_ITEM,
    EXP_CHANGE,
    FISH,
    HARVEST_BLOCK,
    INTERACT_ENTITY,
    INTERACT_LEFT_BLOCK,
    INTERACT_LEFT_AIR,
    INTERACT_LEFT,
    INTERACT_RIGHT_BLOCK,
    INTERACT_RIGHT_AIR,
    INTERACT_RIGHT,
    ITEM_BREAK,
    ITEM_CONSUME,
    ITEM_DAMAGE,
    ITEM_HELD,
    ITEM_MEND,
    LEVEL_CHANGE,
    MOVE,
    PICK_UP_ARROW,
    PICK_UP_ITEM,
    PORTAL,
    RECIPE_DISCOVER,
    RESPAWN,
    RIPTIDE,
    SHEAR_ENTITY,
    SWAP_HAND_ITEMS,
    TAKE_LECTERN_BOOK,
    TELEPORT,
    TOGGLE_SNEAK,
    TOGGLE_SPRINT,
    TOGGLE_FLIGHT,
    UNLEASH_ENTITY,

    //BLOCK
    BLOCK_BREAK,
    BLOCK_DAMAGE_ABORT,
    BLOCK_DAMAGE,
    BLOCK_DISPENSE_ARMOR,
    BLOCK_DISPENSE,
    BLOCK_DROP_ITEM,
    BLOCK_FERTILIZE,
    BLOCK_MULTI_PLACE,
    BLOCK_PLACE,
    SIGN_CHANGE,
    NOTE_PLAY,

    //ENCHANT
    ENCHANT_ITEM,
    PREPARE_ITEM_ENCHANT,

    //WORLD
    LIGHTNING_STRIKE,  //ENTITY RAID INVENTORY VEHICLE

    //TICK
    TICK_TASK,

    //NEW
    SHOOT_BOW,
    DEATH,
    ENTITY_JUMP,
    PLAYER_JUMP,
    PROJECTILE_LAUNCH,
    PROJECTILE_HIT_BLOCK,
    PROJECTILE_HIT_ENTITY,
    ELYTRA_BOOST,
    KILL,
    HUNGER,
    REGAIN_HEALTH,
    PICK_UP_EXPERIENCE,

    BE_TARGETED
}